name: que_dijo_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-113.0.dev <4.0.0'

dependencies:
  audioplayers: ^4.1.0
  aws_s3_upload: ^1.5.0
  camera: ^0.10.5+2
  crypto: ^3.0.3
  cupertino_icons: ^1.0.5
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  flutter_sound: ^9.2.13
  http: ^0.13.6
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.0.15
  permission_handler: ^10.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
